// react-test/src/App.tsx
import { useState } from 'react'
import { uStore } from '@waelio/ustore';
import reactLogo from './assets/react.svg'
import './App.css'

function App() {
  const [count, setCount] = useState(0)
  const label = "test"
  const payload = "ustore payload"
  uStore.local.set(label, payload)
  const test = uStore.local.get(label)

  return (
    <div className="App">
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src="/vite.svg" className="logo" alt="Vite logo" />
        </a>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>        
      </div>
      <h4>Test: {label} = {test}</h4>
    </div>
  )
}

export default App

// vue-test/src/App.vue
<script setup lang="ts">
import { uStore } from "@waelio/ustore";
const label = "test",
payload = "ustore payload"
uStore.local.set(label, payload)
const test = uStore.local.get(label)
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
    <h4>Test: {{label}} = {{test}}</h4>
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
